title: LMPxxxx Basic principles of machine learning in biomedical research (Winter 2022)
description: LMPxxxx course website
sitename: LMPxxxx-uoft
baseurl: '2022'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - contents
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
markdown: kramdown

theme: jekyll-theme-cayman
